typography_spectrum: 0.407657
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.503285509642589
  lightness: 0.8171817865321753
  saturation: 0.32026725805239253
  rhythmicContrast: 0.6490587226316604
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.576576
analytics:
  google: null
  facebook: null
  twitter: null
name: christianleon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Newfangled website
description: AI Designed
purpose: []
